### ISSUE TITLE
Remove common words that are between tags

### ISSUE THREAD

**Issue by Toilal** [wackou/guessit#223]
```
? Project.Runway.S14E00.and.S14E01.(Eng.Subs).SDTV.x264-[2Maverick].mp4
: container: mp4
  episodeList:
  - 0
  - 1
  episodeNumber: 0
  format: TV
  language: en
  mimetype: video/mp4
  releaseGroup: 2Maverick
  season: 14
  series: Project Runway
  title: and
  type: episode
  videoCodec: h264
```

`and` should not be guessed as the title.
